server:
  address: 0.0.0.0
  port: 8088

spring:
  servlet:
    session:
      timeout: 60m

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.meta.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.mybatis: INFO
    com.meta: INFO
    com.zaxxer.hikari: INFO
